version: 2.1
orbs:
  jq: circleci/jq@1.9.1
jobs:
  build-image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bb:7e:3e:43:17:12:36:65:c2:cc:c2:ad:2a:b7:30:2d"
      - checkout
      - jq/install
      # - run:
      #     name: check if image tag already exists
      #     command: |
      #       PLUGIN_VERSION=$(cat Dockerfile | grep "ARG PLUGIN_VERSION=" | cut -d'=' -f2)
      #       CORE_VERSION=$(cat Dockerfile | grep "ARG CORE_VERSION=" | cut -d'=' -f2)
      #       STATUS_CODE=$(curl -I -X GET https://hub.docker.com/v2/repositories/supertokens/supertokens-mysql/tags/${CORE_VERSION}_${PLUGIN_VERSION} -o /dev/null -w '%{http_code}\n' -s)
      #       if [[ $STATUS_CODE -eq "200" ]]
      #       then
      #           echo "version already exists"
      #           exit 1
      #       fi
      - run:
          name: build docker image and test
          command: |
            ./test.sh
            if [[ $? -ne 0 ]]; then exit 1; fi
      - run:
          name: merge with master
          command: |
            PLUGIN_VERSION=$(cat Dockerfile | grep "ARG PLUGIN_VERSION=" | cut -d'=' -f2)
            CORE_VERSION=$(cat Dockerfile | grep "ARG CORE_VERSION=" | cut -d'=' -f2)
            git checkout master
            git merge latest
            git push
            git tag ${CORE_VERSION}_${PLUGIN_VERSION} -f
            git push origin --tags -f
      - run:
          name: check if is latest core and plugin
          command: |
            PLUGIN_VERSION=$(cat Dockerfile | grep "ARG PLUGIN_VERSION=" | cut -d'=' -f2)
            CORE_VERSION=$(cat Dockerfile | grep "ARG CORE_VERSION=" | cut -d'=' -f2)
            PLUGIN_NAME=$(cat Dockerfile | grep "ARG PLUGIN_NAME=" | cut -d'=' -f2)
            response=`curl -s -X GET \
              "https://api.supertokens.io/0/core/latest/check?password=$API_KEY&planType=FREE&version=$CORE_VERSION" \
              -H 'api-version: 0'`
            core_response=`echo $response | jq .isLatest`
            response=`curl -s -X GET \
              "https://api.supertokens.io/0/plugin/latest/check?password=$API_KEY&planType=FREE&version=$PLUGIN_VERSION&name=$PLUGIN_NAME" \
              -H 'api-version: 0'`
            plugin_response=`echo $response | jq .isLatest`
            if [[ $core_response -eq true ]] && [[ $plugin_response -eq true ]]
            then
              git tag latest -f
              git push origin --tags -f
            fi
workflows:
  version: 2
  tagged-build:
    jobs:
      - build-image:
          filters:
            branches:
              only: latest